import { differenceInCalendarDays, subDays } from 'date-fns';
import { patternCopy, type PatternKey } from '../content/copy';
import type { BehaviorPattern, DetectionConfig, EvidenceAlert, Holding, JournalEntry, PatternType, Transaction } from '../types';
import { holdingValue, totalValue } from '../services/portfolio';

const level = (count: number, highAt = 2): 'LOW'|'MODERATE'|'HIGH' => count === 0 ? 'LOW' : count >= highAt ? 'HIGH' : 'MODERATE';
const priceAt = (history: Record<string, { date: string; close: number }[]>, symbol: string, date: string) => history[symbol]?.find((p) => p.date === date)?.close;
const moveBefore = (history: Record<string, { date: string; close: number }[]>, tx: Transaction, days: number) => { const end = new Date(tx.date); const start = subDays(end, days); const points = history[tx.symbol] || []; const a = points.reduce((best, p) => Math.abs(new Date(p.date).getTime() - start.getTime()) < Math.abs(new Date(best?.date || tx.date).getTime() - start.getTime()) ? p : best, points[0]); const b = priceAt(history, tx.symbol, tx.date) || tx.price; return a ? (b - a.close) / a.close * 100 : 0; };
const evidenceAlert = (type: PatternType, date: string, ids: string[], evidence: string[], severity: 'LOW'|'MODERATE'|'HIGH' = 'MODERATE'): EvidenceAlert => ({ id: `${type}_${ids.join('_')}`, patternType: type, severity, detectedAt: date, title: patternCopy[type].title, explanation: evidence[0], evidence, relatedTransactionIds: ids, reflectionQuestion: patternCopy[type].reflection, status: 'NEW' });

export const analyze = (transactions: Transaction[], holdings: Holding[], history: Record<string, { date: string; close: number }[]>, journal: JournalEntry[], config: DetectionConfig, today = new Date()) => {
  const patterns: BehaviorPattern[] = []; const alerts: EvidenceAlert[] = []; const add = (type: PatternType, ids: string[], dates: string[], evidence: string[], explanation: string) => { const key = type as PatternKey; patterns.push({ type, level: level(ids.length), relevantTransactionIds: ids, rule: patternCopy[key].rule, evidence, explanation, reflectionQuestion: patternCopy[key].reflection, detectedDates: dates }); alerts.push(evidenceAlert(type, dates[0] || today.toISOString(), ids, evidence)); };
  const sorted = [...transactions].sort((a, b) => a.date.localeCompare(b.date));
  const fomo = sorted.filter((t) => t.type === 'BUY' && moveBefore(history, t, config.lookbackDays) >= config.fomoRunUpPct && differenceInCalendarDays(today, new Date(t.date)) <= 90);
  if (fomo.length) add('fomo', fomo.map((t) => t.id), fomo.map((t) => t.date), fomo.map((t) => `Bought ${t.symbol} on ${t.date}, after a ${moveBefore(history, t, config.lookbackDays).toFixed(1)}% rise over ${config.lookbackDays} days.`), 'Purchase timing may resemble a FOMO-like pattern, although transaction data cannot establish why it happened.');
  const recent = sorted.filter((t) => differenceInCalendarDays(today, new Date(t.date)) <= config.overtradingWindowDays); const baseline = Math.max(1, transactions.filter((t) => differenceInCalendarDays(today, new Date(t.date)) > 30 && differenceInCalendarDays(today, new Date(t.date)) <= 120).length / 13); if (recent.length >= config.overtradingCount && recent.length >= baseline * 2) add('overtrading', recent.map((t) => t.id), [recent[recent.length - 1]?.date || today.toISOString()], [`${recent.length} transactions in the last ${config.overtradingWindowDays} days versus a typical ${baseline.toFixed(1)} per week.`, 'Recent transaction frequency is unusually high relative to the available baseline.'], 'Recent activity may indicate an overtrading pattern, though a planned strategy could also explain it.');
  const total = totalValue(holdings); const concentrated = holdings.filter((h) => holdingValue(h) / (total || 1) * 100 >= config.concentrationPct); if (concentrated.length) concentrated.forEach((h) => { const share = holdingValue(h) / total * 100; add('concentration', transactions.filter((t) => t.symbol === h.symbol).map((t) => t.id), [today.toISOString()], [`${share.toFixed(0)}% of the portfolio is currently allocated to ${h.symbol}.`, `Holding value ${holdingValue(h).toFixed(0)} ÷ portfolio value ${total.toFixed(0)} × 100 = ${share.toFixed(1)}%.`], 'This allocation may deserve a review against the intended investment strategy.'); });
  const panic = sorted.filter((t) => t.type === 'SELL' && -moveBefore(history, t, config.lookbackDays) >= config.panicDropPct); if (panic.length) add('panic', panic.map((t) => t.id), panic.map((t) => t.date), panic.map((t) => `Sold ${t.symbol} on ${t.date}, after a ${Math.abs(moveBefore(history, t, config.lookbackDays)).toFixed(1)}% decline over ${config.lookbackDays} days.`), 'Recent activity may indicate a short-term reaction pattern; the data does not establish the reason for the sale.');
  const loss = holdings.filter((h) => (h.currentPrice / h.avgBuyPrice - 1) * -100 >= config.lossAversionDrawdownPct && transactions.some((t) => t.symbol === h.symbol && differenceInCalendarDays(today, new Date(t.date)) >= config.lossAversionMinHoldDays && t.type === 'BUY') && journal.some((j) => j.symbol === h.symbol && j.updates.some((u) => u.thesisChanged))); if (loss.length) loss.forEach((h) => { const ids = transactions.filter((t) => t.symbol === h.symbol).map((t) => t.id); add('lossAversion', ids, [today.toISOString()], [`${h.symbol} is down ${Math.abs((h.currentPrice / h.avgBuyPrice - 1) * 100).toFixed(1)}% from average cost and has been held for more than ${config.lossAversionMinHoldDays} days.`, 'A linked journal update marks the original thesis as changed.'], 'This combination can resemble a loss-aversion pattern, but the data cannot establish the user’s motivation.'); });
  const timing = sorted.filter((t) => differenceInCalendarDays(today, new Date(t.date)) <= 30 && Math.abs(moveBefore(history, t, config.lookbackDays)) >= config.timingMovePct); if (timing.length >= config.marketTimingMinTrades) add('timing', timing.map((t) => t.id), timing.map((t) => t.date), [`${timing.length} trades occurred shortly after price movements of at least ${config.timingMovePct}%.`, `Window: ${timing[0].date} to ${timing[timing.length - 1]?.date}.`], 'Several recent trades may indicate a market-timing pattern; a predefined strategy could also explain them.');
  return { patterns, alerts };
};
