import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { analyze } from '../engine/analyzer';
import { defaultConfig, freshDemo } from '../lib/mockData';
import type { AlertStatus, AppState, DetectionConfig, JournalEntry, Transaction } from '../types';
import { holdingsFromTransactions } from '../services/portfolio';

const initial = { isAuthenticated: false, isDemo: false, profile: { name: '', email: '' }, transactions: [], priceHistory: {}, holdings: [], journal: [], alerts: [], patterns: [], config: defaultConfig, theme: 'dark' as const };
const reanalyze = (state: AppState) => { const holdings = holdingsFromTransactions(state.transactions, state.holdings.length ? state.holdings : freshDemo().holdings); const result = analyze(state.transactions, holdings, state.priceHistory, state.journal, state.config); const prior = new Map(state.alerts.map((a) => [a.id, a.status])); return { ...state, holdings, patterns: result.patterns, alerts: result.alerts.map((a) => ({ ...a, status: prior.get(a.id) || a.status })) }; };

interface Actions { login: (email: string, name?: string) => void; demo: () => void; logout: () => void; addTransaction: (t: Transaction) => void; deleteTransaction: (id: string) => void; setAlertStatus: (id: string, status: AlertStatus) => void; saveJournal: (j: JournalEntry) => void; updateConfig: (c: Partial<DetectionConfig>) => void; resetDemo: () => void; clearAll: () => void; toggleTheme: () => void; runAnalysis: () => void; }

export const useInvestGuard = create<AppState & Actions>()(persist((set) => ({ ...initial, login: (email, name = email.split('@')[0]) => set((s) => ({ ...s, isAuthenticated: true, profile: { email, name } })), demo: () => set(() => { const data = freshDemo(); return reanalyze({ ...initial, isAuthenticated: true, isDemo: true, profile: { name: 'Aarav Mehta', email: 'demo@investguard.app' }, ...data }); }), logout: () => set((s) => ({ ...s, isAuthenticated: false })), addTransaction: (t) => set((s) => reanalyze({ ...s, transactions: [...s.transactions, t] })), deleteTransaction: (id) => set((s) => reanalyze({ ...s, transactions: s.transactions.filter((t) => t.id !== id) })), setAlertStatus: (id, status) => set((s) => ({ ...s, alerts: s.alerts.map((a) => a.id === id ? { ...a, status } : a) })), saveJournal: (j) => set((s) => reanalyze({ ...s, journal: [...s.journal.filter((x) => x.id !== j.id), j] })), updateConfig: (c) => set((s) => reanalyze({ ...s, config: { ...s.config, ...c } })), resetDemo: () => set(() => { const data = freshDemo(); return reanalyze({ ...initial, isAuthenticated: true, isDemo: true, profile: { name: 'Aarav Mehta', email: 'demo@investguard.app' }, ...data }); }), clearAll: () => set((s) => ({ ...initial, isAuthenticated: s.isAuthenticated, profile: s.profile })), toggleTheme: () => set((s) => ({ ...s, theme: s.theme === 'light' ? 'dark' : 'light' })), runAnalysis: () => set((s) => reanalyze(s)) }), { name: 'investguard_v1', version: 2, migrate: (persisted) => ({ ...(persisted as AppState), theme: 'dark' }), partialize: (s) => ({ ...s }) }));
