import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Holding } from '../types';
import { allocation, sectorExposure } from '../services/portfolio';
import { money } from '../lib/format';

const colors = ['#6c63ff', '#2dbb9a', '#f1b24a', '#f07167', '#8c7cf3', '#5c8df6'];
export type PerformanceRange = 'day' | 'month' | 'year';
export const PerformanceChart = ({ holdings, range = 'month' }: { holdings: Holding[]; range?: PerformanceRange }) => { const base = holdings.reduce((s, h) => s + h.quantity * h.avgBuyPrice, 0) || 100000; const labels = range === 'day' ? ['09:00','10:00','11:00','12:00','13:00','14:00','15:00'] : range === 'year' ? ['2022','2023','2024','2025','2026'] : ['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep']; const data = labels.map((label, i) => ({ label, value: Math.round(base * (range === 'day' ? (0.982 + i * .002 + Math.sin(i) * .002) : range === 'year' ? (0.79 + i * .045 + Math.sin(i / 1.5) * .025) : (0.93 + i * 0.006 + Math.sin(i / 2) * 0.018))) })); return <ResponsiveContainer width="100%" height={245}><LineChart data={data} margin={{ top: 8, right: 10, left: -16, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e7ebf2"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#8a94a6', fontSize: 12 }}/><YAxis hide/><Tooltip formatter={(v) => money(Number(v))} contentStyle={{ borderRadius: 12, border: '1px solid #e7ebf2', boxShadow: '0 8px 24px rgba(15,23,42,.08)' }}/><Line type="monotone" dataKey="value" stroke="#655cf6" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer>; };
export const AllocationChart = ({ holdings }: { holdings: Holding[] }) => <ResponsiveContainer width="100%" height={205}><PieChart><Pie data={allocation(holdings)} dataKey="value" nameKey="name" innerRadius={58} outerRadius={82} paddingAngle={4} stroke="none">{allocation(holdings).map((e, i) => <Cell key={e.name} fill={colors[i % colors.length]}/>)}</Pie><Tooltip formatter={(v) => money(Number(v))}/></PieChart></ResponsiveContainer>;
export const SectorChart = ({ holdings }: { holdings: Holding[] }) => <ResponsiveContainer width="100%" height={220}><BarChart data={sectorExposure(holdings)} layout="vertical" margin={{ top: 0, right: 12, left: 10, bottom: 0 }}><CartesianGrid horizontal={false} stroke="#e7ebf2"/><XAxis type="number" hide/><YAxis type="category" dataKey="name" axisLine={false} tickLine={false} width={80} tick={{ fill: '#697386', fontSize: 12 }}/><Tooltip formatter={(v) => `${Number(v).toFixed(1)}%`}/><Bar dataKey="percent" fill="#655cf6" radius={[0, 6, 6, 0]} barSize={15}/></BarChart></ResponsiveContainer>;
