import { NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { BarChart3, BellRing, BookOpen, BrainCircuit, ChevronRight, CircleHelp, FileText, Home, LayoutDashboard, LogOut, Menu, Moon, NotebookPen, PieChart, Settings, Sun, Target, TrendingUp, WalletCards, X } from 'lucide-react';
import { useState } from 'react';
import { useInvestGuard } from '../store/useInvestGuard';
import { disclaimer } from '../content/copy';
import AgentWidget from './AgentWidget';

const nav = [
  { to: '/dashboard', label: 'Overview', icon: LayoutDashboard }, { to: '/portfolio', label: 'Portfolio', icon: PieChart }, { to: '/transactions', label: 'Transactions', icon: TrendingUp }, { to: '/behavior', label: 'Behavior analysis', icon: BrainCircuit }, { to: '/alerts', label: 'Smart alerts', icon: BellRing }, { to: '/journal', label: 'Investment journal', icon: NotebookPen }, { to: '/planner', label: 'Investment planner', icon: Target }, { to: '/learn', label: 'Learn', icon: BookOpen },
];

export default function Layout() { const [open, setOpen] = useState(false); const location = useLocation(); const navigate = useNavigate(); const { profile, isDemo, theme, toggleTheme, logout } = useInvestGuard(); const active = nav.find((n) => location.pathname.startsWith(n.to)); const ThemeIcon = theme === 'light' ? Moon : Sun; return <div className={`app-shell ${theme}`}><aside className={`sidebar ${open ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><BarChart3 size={19}/></div><div><strong>InvestGuard</strong><span>behavioral clarity</span></div><button className="mobile-close" onClick={() => setOpen(false)}><X size={18}/></button></div><div className="workspace"><span className="avatar">{profile.name?.slice(0, 1) || 'A'}</span><div><strong>{profile.name || 'Demo investor'}</strong><span>{isDemo ? 'Demo workspace' : 'Personal workspace'}</span></div><ChevronRight size={15}/></div><nav>{nav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className={({ isActive }) => isActive ? 'active' : ''}><Icon size={18}/><span>{label}</span>{label === 'Smart alerts' && <span className="nav-count">{useInvestGuard.getState().alerts.filter((a) => a.status === 'NEW').length}</span>}</NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/settings" className={location.pathname === '/settings' ? 'active' : ''}><Settings size={18}/><span>Settings</span></NavLink><button onClick={toggleTheme}><ThemeIcon size={18}/><span>{theme === 'light' ? 'Dark mode' : 'Light mode'}</span></button><button onClick={() => { logout(); navigate('/login'); }}><LogOut size={18}/><span>Sign out</span></button></div></aside><main className="main"><header className="topbar"><button className="menu-btn" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={20}/></button><div className="breadcrumbs"><span>{active?.label || 'InvestGuard'}</span>{isDemo && <span className="demo-chip">DEMO DATA</span>}</div><div className="top-actions"><button className="help-btn" title="Help"><CircleHelp size={18}/></button><span className="top-avatar">{profile.name?.slice(0, 1) || 'A'}</span></div></header><div className="content"><Outlet /></div><footer>{disclaimer}</footer><AgentWidget/></main></div>; }
